routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*

|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('/product','ProductController');
Route::get('/child/{id}','ProductController@childs');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use SoftDeletes;

//use Illuminate\Database\Eloquent\SoftDeletes;



class Product extends Model
{
    protected $guarded = ['id'];
    protected $hidden = ['created_at','updated_at'];

    public function category(){
        return $this->belongsTo(Category::class);
    }
    public function tags()
    {
        return $this->belongsToMany(Tag::class);
    }




}

app/Http/Controllers/ProductController.php
<?php

namespace App\Http\Controllers;

use App\Tag;
use App\Category;
use App\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {

        $products = Product::query();

        if($request->filled('search')){
            $products = Product::where(function ($q)use ($request){
//            $products = $products->where('tags',function ($query)use ($request){
                $q->where('name','like', '%'. $request->search .'%');
                $q->orWhere('description', 'like', '%' . $request->search . '%');
            });
        }


        if($request->filled('tag')){
            $products = $products->whereHas('tags',function ($query)use ($request){
                $query->where('name','like', '%'. $request->tag .'%');
            });
        }

        if($request->filled('parent_category_id')){
            $products = $products->whereHas('category',function ($category) use($request){
                $category->where('parent_id',$request->parent_category_id);
            });
        }

        $products = $products->paginate(5);
        $categories = Category::where('parent_id',0)->get();
        return view('products.index',compact('products','categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $tags = Tag::all();
        $categories = Category::where('parent_id',0)->get();
        return view('products.create',compact('categories','items','tags'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
//        dd($request->all());
        $items =[
            'name' => 'required',
            'category_id' => 'required',
            'description' => 'required',
            'quantity' => 'required',
            'buy_price' => 'required',
            'sell_price' => 'required',
            'quantity' => 'required',
            'tag_id' => 'required',
        ];
        $message =[
            'name.required'=>'اسم المنتج مطلوب',
            'category_id.required'=>' التصنيف الرئيسي مطلوب',
            'description.required'=>' الوصف مطلوب',
            'buy_price.required'=>' سعر الشراء مطلوب',
            'sell_price.required'=>' سعر البيع مطلوب',
            'quantity.required'=>' الكميه مطلوب',
            'pic.required'=>'صوره المنتج مطلوبه'

        ];
        $this->validate($request,$items,$message);
        $product = new Product();
        $product->name = $request->name;
        $product->description = $request->description;
        $product->buy_price = $request->buy_price;
        $product->sell_price = $request->sell_price;
        $product->quantity = $request->quantity;
        $product->category_id = $request->branch;

//dd($request->pic);
        if ( $request->hasFile('pic')  ) {
//            dd($request->pic);
            $image = $request->pic;
            $image_new_name = time() . $image->getClientOriginalName();
            $image->move(public_path().'/product', $image_new_name);
            $product->image = $image_new_name;

        }
        $product->save();




        $tag = $request->tag_id;
        //dd($tag);
        $product->tags()->sync($tag);
        return redirect(url('product'))->with('success','تمت الاضافه بنجاح');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {

    }

    public function childs( $id )
    {

        $cats = Category::where("parent_id", $id)->select("id", "category_name")->get();
        $html = "";
        $html.= "<option value=''>كل التصنيفات الفرعيه</option>" ;
        foreach ($cats as $cat) {
            $html .= "<option value='" . $cat->id . "'>" . $cat->category_name . "</option>";
        }
        return response()->json(["status" => true, 'data' => $html]);

    }

    }

resources/views/products/create.blade.php
@extends('layouts.app')


@section('content')
    <div class="ibox float-e-margins">
        <div><h1 style="margin-right: 10px">اضافه منتج جديد</h1></div>
        <br>
    <div class="ibox-content">


        @include('alerts')
        <form action="{{url('product')}}" method="post"  class="form-horizontal" enctype="multipart/form-data">
            {{csrf_field()}}

            {{--create parent_id--}}
            {{--<input type="hidden" name="parent_id"  class="form-control">--}}

            <div class="form-group"><label class="col-sm-2 control-label">اسم المنتج</label>

                <div class="col-sm-10"><input type="text" name="name" class="form-control" value="{{old('name')}}"></div>
            </div>

            <div class="form-group"><label class="col-sm-2 control-label">التصنيف الرئيسي</label>
                <div class="col-sm-10">
                    <select class="form-control m-b" name="category_id" id="mainCategory"  >
                        <option value="" disabled selected hidden>اختيار الكل</option>
                        @foreach($categories as $category)
                            <option  value="{{$category->id}}" {{ (collect(old('category_name'))->contains($category->id)) ? 'selected':'' }}>{{$category->category_name}}</option>
                        @endforeach
                    </select>
                </div>
            </div>
            <div class="form-group"><label class="col-sm-2 control-label">التصنيف الفرعي</label>
                <div class="col-sm-10">
                    <select class="form-control m-b" name="branch" id="branch" >
                        <option value="" disabled selected hidden>اختيار الكل</option>

                        {{--@foreach($items as $item)--}}
                        {{--<option value="{{$item->category_name}}">{{$item->category_name}}</option>--}}
                        {{--@endforeach--}}

                    </select>
                </div>
            </div>
            <div class="row">
                <div class="form-group"><label class="col-sm-2 control-label">صوره المنتج</label>

                    <div class="col-sm-10"><input type="file" name="pic" class="form-control" style="margin-right: 11px"></div>
                </div>

            </div>
            <div class="form-group"><label class="col-sm-2 control-label">سعر الشراء</label>

                <div class="col-sm-10"><input id="buy_price" type="number" name="buy_price" class="form-control" value="{{old('price')}}"></div>
            </div>
            <div class="form-group"><label class="col-sm-2 control-label">سعر البيع</label>

                <div class="col-sm-10"><input type="number" name="sell_price" class="form-control" value="{{old('price')}}"></div>
            </div>
            <div class="form-group"><label class="col-sm-2 control-label">الكميه</label>

                <div class="col-sm-10"><input id="quantity" type="number" name="quantity" class="form-control" value="{{old('quantity')}}"></div>
            </div>



            <div class="row">
                <div class="col-lg-12">
                    {{--<div class="ibox-title">--}}
                        <h3 style="margin-right: 0px;">وصف المنتج</h3>
                        <div class="ibox-content ">
                            <textarea class="summernote form-group" cols="10" rows="10" name="description">
                                {{old('description')}}
                            </textarea>
                        </div>
                </div>
            </div>
            <div class="row" style="margin-top: 10px;margin-right: -190px">

                    {{--<div class="multiselect">--}}
                        <h3 class="col-sm-2 control-label" style="margin-right: 60px;">التاجات</h3>


                        <select class="js-example-basic-multiple " id="tags" name="states[]" multiple="multiple">
                            @foreach($tags as $tag)
                            <option value="{{$tag->id}}" name="tag_id[]">{{$tag->name}}</option>
                            @endforeach
                        </select>




                        {{--<div class="selectBox" onclick="showCheckboxes()">--}}
                            {{--<select>--}}
                                {{--<option>اختر من هنا</option>--}}
                            {{--</select>--}}
                        {{--<div id="checkboxes">--}}
                            {{--@foreach($tags as $tag)--}}
                            {{--<label for="one">--}}
                                {{--<input type="checkbox" value="{{$tag->id}}" name="tag_id[]">{{$tag->name}}</label>--}}
                            {{--@endforeach--}}
                        {{--</div>--}}
                    </div>
                </div>
            </div>
            <div class="form-group" id="show" style="display: none" ><label class="col-sm-2 control-label" style="text-align: center;">التكلفه</label>

                <div class="col-sm-10"><input id="cost"    class="form-control"  ></div>
            </div>
            <div class="text-center">
                <button  type="submit" class="btn btn-primary btn-rounded bg-success " >
                    حفظ
                </button>
            </div>
        </form>
        <div class="row" style="margin-top: 5px;">
        </div>
    </div>
    </div>
@stop
@push('scripts')
    <!-- SUMMERNOTE -->
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>


    <script src="{{asset('assets/js/plugins/summernote/summernote.min.js')}}"></script>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script>
        $(document).ready(function(){
            $('.summernote').summernote();
            $("#mainCategory").change(function (e) {
                e.preventDefault();

                var catId = $(this).val();
                // console.log(catId)
                // let data = {catId}
                axios.get('{{url('child')}}'+'/' + catId)
                    .then(function (response) {
                        console.log(response.data.status);

                        if (response.data.status == true){
                            // var tt = "" ;
                            $("#branch").empty().append(response.data.data)

                        }
                    })
                // .catch(function (error) {
                //     console.log(error);
                // })
                // .then(function () {
                //     // always executed
                // });



            });


                $('#buy_price,#quantity').on('keydown ', function() {
                    var buy_price = $('#buy_price').val();
                    var qnt = $('#quantity').val();
                    var cost = buy_price * qnt;
                        // alert(cost);

                        $("#cost").val(cost);
                        $("#show").show();

                    // });
                });


        })

        $(document).ready(function() {
            $('.js-example-basic-multiple').select2();
        });


    </script>
@endpush


@push('styles')

    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />

    <link href="{{asset('assets/css/css/plugins/summernote/summernote.css')}}" rel="stylesheet">
    <link href="{{asset('assets/css/css/plugins/summernote/summernote-bs3.css')}}" rel="stylesheet">
    <style>
        .note-editor.note-frame .note-editing-area .note-editable{
            height: 200px;
        }

        .selectBox select {
            width: 100%;
            font-weight: bold;
        }


        #checkboxes label {
            display: block;

        }

        #checkboxes label:hover {
            background-color: #1e90ff;
        }

        .ibox-content{
            margin-right: 73px;
            background-color: ghostwhite;
        }


        .form-horizontal .form-group{
            margin-right: -124px;
        }
        .selectBox select{
            margin-right: 71px;
        }
        #tags{
            width: 247px;
        }

    </style>
@endpush

resources/views/products/index.blade.php
@extends('layouts.app')
@section('content')

    <form>

        <div class="row"style="margin-top: 10px">
            <div class="form-group"><label class="col-sm-2 control-label" style="text-align: center"> اسم المنتج او الوصف</label>

                <div class="col-sm-8"><input type="text" name="search" class="form-control" value="{{request('search')}}"></div>
            </div>
        </div>
        <div class="row"style="margin-top: 10px" >
            <div class="form-group"><label class="col-sm-2 control-label" style="text-align: center">التصنيف الرئيسي</label>

                <div class="col-sm-4"><select id="mainCategory" name="parent_category_id"   class=" form-control">
                        <option value=""> كل التصنيفات</option>
                        @foreach($categories as $category)
                            <option value="{{$category->id}}" @if(request('parent_category_id') == $category->id){{'selected'}}@endif>{{$category->category_name}}
                            </option>
                        @endforeach
                    </select>
                </div>
            </div>

            <div class="form-group" style="margin-top: -16px"><label class="col-md-2 control-label"> التاج </label>

                <div class="col-sm-4"><input type="text" name="tag" class=" form-control"
                                              value="{{request('tag')}}"
                                              placeholder=" التاج" style="margin-right: -151px;margin-left: 213px"></div>
            </div>

        </div>
        <div class="row">
            <div class="col-lg-2 text-center " style="margin-top: 2em;margin-right: 500px">
                <button type="submit" class="btn btn-primary" style="font-size: 20px">عرض</button>
            </div>
        </div>
    </form>


    <div class="wrapper wrapper-content">
        <div class="col-md-4 col-md-push-8">
            <a type="button" class="btn btn-primary btn-rounded bg-success" href="{{route('product.create')}}">
                اضافه منتج
            </a>

        </div>
    </div>
    <div class="col-md-12">
        <div class="ibox float-e-margins">
            @include('alerts')
            <div class="ibox-content">

                <table class="table table-bordered">
                    <thead class="thead-light">
                    <tr >
                        <th scope="col">اسم المنتج</th>
                        <th scope="col">الوصف</th>
                        <th scope="col">التصنيف </th>
                        <th scope="col">التاجات</th>


                    </tr>
                    </thead>
                    <tbody>
                    @foreach($products as $product)
                        <tr>
                            <th scope="row">
                                {{$product->name}}
                            </th>
                            <th scope="row">
                                {{$product->description}}
                            </th>
                            <th scope="row">
                              {{( $product->category ) ? $product->category->parent['category_name']:"لا يوجد" }}
                            </th>

                            <th scope="row">
                                @foreach($product->tags as $tag)
                              {{$tag->name}},
                                @endforeach
                            </th>


                        </tr>
                    @endforeach
                    </tbody>
                </table>

            </div>


        </div>
        <div class="ibox float-e-margins">
            <div class="ibox-title text-center ">
                {{$products->onEachSide(1)->appends(Request::capture()->except('page'))->render() }}
            </div>
        </div>
    </div>
@stop
@push('styles')
    <style>
        th{
            text-align: center;
        }
        .form-control{
            display: inline-block;
            width: -webkit-fill-available;
        }
    </style>
    @endpush
@push('scripts')
    <script>

        $(document).on("click",".delete", function (e) {
            e.preventDefault()
            // alert("asasa") ;
            // console.log("dsdsdss")

// alert();
            /* get data from button */
            var id = $(this).data("id");
// console.log("id",id);
            /* set action attribute to new url */
            $('#deleteform').attr('action', '{{url("product")}}' + '/' + id);
            /* open the modal */
            $('#deleteModal').modal('show');
        })
    </script>
@endpush