routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*

|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});
Route::resource('/product','ProductController');
Route::get('/child/{id}','ProductController@childs');

resources/views/layouts/admin-nav.blade.php
<nav class="navbar-default navbar-static-side" role="navigation">
    <div class="sidebar-collapse">
        <ul class="nav metismenu" id="side-menu">
            <li class="nav-header">
                <div class="dropdown profile-element"> <span>
                            <img id="img" alt="image" class="img-circle" src="{{asset('public/product/profile_small.jpg')}}" />
                             </span>
                    <a data-toggle="dropdown" class="dropdown-toggle" href="#">
                            <span class="clear"> <span class="block m-t-xs"> <strong class="font-bold">Admin</strong>
                             </span> <span class="text-muted text-xs block">Art Developer</span> </span> </a>

                </div>
                <div class="logo-element">
                    IN+
                </div>
            </li>

            {{--<li>--}}
                {{--<a href="{{route('product.index')}}"><i class="fa fa-th-large"></i> <span class="nav-label">الرئيسيه</span></a>--}}
            {{--</li>--}}


            {{--<li>--}}

                {{--{{dd("sdsd" , $categories)}}--}}
                {{--<a href="#"><i class="fa fa-th-list"></i> <span class="nav-label">الاقسام</span> <span class="fa arrow"></span></a>--}}
                {{--<ul class="nav nav-second-level collapse">--}}
                    {{--@foreach($categories as $category)--}}
                    {{--<li><a href="{{url("/prod/{$category->id}")}}">{{$category->category_name}}</a></li>--}}
                    {{--@endforeach--}}
                {{--</ul>--}}
            {{--</li>--}}
            {{--<li>--}}
                {{--<a href="{{url('/order')}}"><i class="fa fa-first-order"></i> <span class="nav-label">الطلبات</span></a>--}}
            {{--</li>--}}
            {{--<li>--}}
                {{--<a href="{{route('image.index')}}"><i class="fa fa-address-card"></i> <span class="nav-label">صور سليدر</span></a>--}}
            {{--</li>--}}
            {{--<li>--}}
                {{--<a href="{{url('/contacts')}}"><i class="fa fa-address-card"></i> <span class="nav-label">الاتصال</span></a>--}}
            {{--</li>--}}
        </ul>

    </div>
</nav>
<div id="page-wrapper" class="gray-bg">
    <div class="row border-bottom">
<nav class="navbar navbar-static-top white-bg" role="navigation" style="margin-bottom: 0">
    <div class="navbar-header">
        {{--<a class="navbar-minimalize minimalize-styl-2 btn btn-primary " href="#"><i class="fa fa-bars"></i> </a>--}}
        {{--<input value="{{request('search')}}" type="text" name="search" placeholder="Search for something..." class="form-control" >--}}

        {{--<form role="search" class="navbar-form-custom" action="">--}}
            {{--<div class="form-group">--}}
                {{--<div class="">--}}
                    {{--<div class="input-group m-b" >--}}
                        {{--<input id="m" value="{{request('search')}}" type="text" name="search" placeholder="Search for something..." class="form-control">--}}
                        {{--<span class="input-group-btn">--}}
                            {{--<button type="submit" class="btn btn-primary">search</button>--}}
                        {{--</span>--}}
                    {{--</div>--}}
                {{--</div>--}}
            {{--</div>--}}
            {{--<div class="form-group">--}}
                {{--<button type="submit" class="btn btn-sm btn-white" style="float: left; font-size: 15px ; margin-left:-12px" >بحث</button>--}}
            {{--</div>--}}
        {{--</form>--}}


    </div>
    {{--<ul class="nav navbar-top-links navbar-right">--}}

        {{--<li class="dropdown">--}}

            {{--<ul class="dropdown-menu dropdown-messages">--}}
                {{--<li>--}}
                    {{--<div class="dropdown-messages-box">--}}
                        {{--<a href="profile.html" class="pull-left">--}}
                            {{--<img alt="image" class="img-circle" src="img/a7.jpg">--}}
                        {{--</a>--}}
                        {{--<div>--}}
                            {{--<small class="pull-right">46h ago</small>--}}
                            {{--<strong>Mike Loreipsum</strong> started following <strong>Monica Smith</strong>. <br>--}}
                            {{--<small class="text-muted">3 days ago at 7:58 pm - 10.06.2014</small>--}}
                        {{--</div>--}}
                    {{--</div>--}}
                {{--</li>--}}
                {{--<li class="divider"></li>--}}
                {{--<li>--}}
                    {{--<div class="dropdown-messages-box">--}}
                        {{--<a href="profile.html" class="pull-left">--}}
                            {{--<img alt="image" class="img-circle" src="img/a4.jpg">--}}
                        {{--</a>--}}
                        {{--<div>--}}
                            {{--<small class="pull-right text-navy">5h ago</small>--}}
                            {{--<strong>Chris Johnatan Overtunk</strong> started following <strong>Monica Smith</strong>. <br>--}}
                            {{--<small class="text-muted">Yesterday 1:21 pm - 11.06.2014</small>--}}
                        {{--</div>--}}
                    {{--</div>--}}
                {{--</li>--}}
                {{--<li class="divider"></li>--}}
                {{--<li>--}}
                    {{--<div class="dropdown-messages-box">--}}
                        {{--<a href="profile.html" class="pull-left">--}}
                            {{--<img alt="image" class="img-circle" src="img/profile.jpg">--}}
                        {{--</a>--}}
                        {{--<div>--}}
                            {{--<small class="pull-right">23h ago</small>--}}
                            {{--<strong>Monica Smith</strong> love <strong>Kim Smith</strong>. <br>--}}
                            {{--<small class="text-muted">2 days ago at 2:30 am - 11.06.2014</small>--}}
                        {{--</div>--}}
                    {{--</div>--}}
                {{--</li>--}}
                {{--<li class="divider"></li>--}}
                {{--<li>--}}
                    {{--<div class="text-center link-block">--}}
                        {{--<a href="mailbox.html">--}}
                            {{--<i class="fa fa-envelope"></i> <strong>Read All Messages</strong>--}}
                        {{--</a>--}}
                    {{--</div>--}}
                {{--</li>--}}
            {{--</ul>--}}
        {{--</li>--}}
        {{--<li class="dropdown">--}}

            {{--<ul class="dropdown-menu dropdown-alerts">--}}
                {{--<li>--}}
                    {{--<a href="mailbox.html">--}}
                        {{--<div>--}}
                            {{--<i class="fa fa-envelope fa-fw"></i> You have 16 messages--}}
                            {{--<span class="pull-right text-muted small">4 minutes ago</span>--}}
                        {{--</div>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li class="divider"></li>--}}
                {{--<li>--}}
                    {{--<a href="profile.html">--}}
                        {{--<div>--}}
                            {{--<i class="fa fa-twitter fa-fw"></i> 3 New Followers--}}
                            {{--<span class="pull-right text-muted small">12 minutes ago</span>--}}
                        {{--</div>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li class="divider"></li>--}}
                {{--<li>--}}
                    {{--<a href="grid_options.html">--}}
                        {{--<div>--}}
                            {{--<i class="fa fa-upload fa-fw"></i> Server Rebooted--}}
                            {{--<span class="pull-right text-muted small">4 minutes ago</span>--}}
                        {{--</div>--}}
                    {{--</a>--}}
                {{--</li>--}}
                {{--<li class="divider"></li>--}}
                {{--<li>--}}
                    {{--<div class="text-center link-block">--}}
                        {{--<a href="notifications.html">--}}
                            {{--<strong>See All Alerts</strong>--}}
                            {{--<i class="fa fa-angle-right"></i>--}}
                        {{--</a>--}}
                    {{--</div>--}}
                {{--</li>--}}
            {{--</ul>--}}
        {{--</li>--}}
        {{--@if(auth()->guard('web')->check())--}}

            {{--<li class="c">--}}
                {{--<a href="#"  onclick="document.getElementById('logout-form').submit();">--}}
                    {{--<i class="fa fa-sign-out"></i> Log out--}}
                {{--</a>--}}
            {{--</li>--}}
            {{--@else--}}

            {{--<li class="c">--}}
                {{--<a href="{{ route('login') }}">--}}
                    {{--<i class="fa fa-sign-out"></i> Log in--}}
                {{--</a>--}}
            {{--</li>--}}
            {{--<li>--}}
                {{--<a href="{{ route('register') }}">--}}
                    {{--<i class="fa fa-sign-out"></i> register--}}
                {{--</a>--}}
            {{--</li>--}}
            {{--@elseif(auth()->guard('admin')->check())--}}

        {{--<ul class="nav navbar-top-links navbar-left">--}}

            {{--<li>--}}
                {{--<a class="ss" href="#" onclick="document.getElementById('logout-form1').submit();">--}}
                    {{--<i class="fa fa-sign-out"></i>logout--}}
                {{--</a>--}}
            {{--</li>--}}
        {{--</ul>--}}
        {{--<form id="logout-form1" action="{{ route('logout') }}" method="get" style="display: none;">--}}
            {{--{{ csrf_field() }}--}}
        {{--</form>--}}

    {{--</ul>--}}
    {{--@endif--}}
    {{--<div class="lang">--}}
       {{--<span> <a id="arabic" href="{{url('lang/ar')}}">عربي</a></span>--}}
        {{--<span> <a id="en" href="{{url('lang/en')}}">EN</a></span>--}}
    {{--</div>--}}


</nav>
        {{--<form id="logout-form" action="{{ route('logout') }}" method="post" style="display: none;">--}}
            {{--{{ csrf_field() }}--}}
        {{--</form>--}}
        @stack("styles")
            <style>
              #m  {
                   width: 300px;
                  text-align: center;
                }
              .c {
                    padding-right: 200px;
                }
              .ss{
                  margin-right: 200px;
              }
              .lang{
                  float: left;
                 /*margin-right: 500px;*/
                 margin-top: 18px;
                 font-size: 18px;
                  margin-right: 665px;
              }
                #arabic
                {
                 color: red;
                 border-left: 2px solid #1b6d85;
                    padding: 0 .5rem;
                }
                #en
                {
                    padding: 0 .5rem;
                    color: #1b1b1b;

                }
                #img{
                    width: 30px;
                    height: 30px;
                }

            </style>

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title></title>

    @include('layouts.styles')
</head>
<body>

@include('layouts.admin-nav')
</div>
@yield('content')

</div>
@yield('styles')
@include('layouts.scripts')
@yield('scripts')

</body>
</html>

resources/views/layouts/scripts.blade.php
<!-- Mainly scripts -->
<script src="{{asset('assets/js/jquery-3.1.1.min.js')}}"></script>
<script src="{{asset('assets/js/bootstrap.min.js')}}"></script>

<script src="{{asset('assets/js/plugins/metisMenu/jquery.metisMenu.js')}}"></script>
<script src="{{asset('assets/js/plugins/slimscroll/jquery.slimscroll.min.js')}}"></script>

<!-- Flot -->
<script src="{{asset('assets/js/plugins/flot/jquery.flot.js')}}"></script>
<script src="{{asset('assets/js/plugins/flot/jquery.flot.tooltip.min.js')}}"></script>
<script src="{{asset('assets/js/plugins/flot/jquery.flot.spline.js')}}"></script>
<script src="{{asset('assets/js/plugins/flot/jquery.flot.resize.js')}}"></script>
<script src="{{asset('assets/js/plugins/flot/jquery.flot.pie.js')}}"></script>
<script src="{{asset('assets/js/plugins/flot/jquery.flot.symbol.js')}}"></script>
<script src="{{asset('assets/js/plugins/flot/jquery.flot.time.js')}}"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>

<!-- Peity -->
<script src="{{asset('assets/js/plugins/peity/jquery.peity.min.js')}}"></script>
<script src="{{asset('assets/js/demo/peity-demo.js')}}"></script>

<!-- Custom and plugin javascript -->
<script src="{{asset('assets/js/inspinia.js')}}"></script>
<script src="{{asset('assets/js/plugins/pace/pace.min.js"')}}></script>

<!-- jQuery UI -->
<script src="{{asset('assets/js/plugins/jquery-ui/jquery-ui.min.js')}}"></script>

<!-- Jvectormap -->
<script src="{{asset('assets/js/plugins/jvectormap/jquery-jvectormap-2.0.2.min.js')}}"></script>
<script src="{{asset('assets/js/plugins/jvectormap/jquery-jvectormap-world-mill-en.js')}}"></script>

<!-- EayPIE -->
<script src="{{asset('assets/js/plugins/easypiechart/jquery.easypiechart.js')}}"></script>

<!-- Sparkline -->
<script src="{{asset('assets/js/plugins/sparkline/jquery.sparkline.min.js')}}"></script>

<!-- Sparkline demo data  -->
<script src="{{asset('assets/js/demo/sparkline-demo.js')}}"></script>

{{--<!--<script src="js/plugins/datapicker/bootstrap-datepicker.js"></{{asset('assets/script>-->--}}


{{--<!-- Data picker -->--}}
{{--<script src="{{asset('assets/js/plugins/datapicker/bootstrap-datepicker.js')}}"></script>--}}





<script>
    $(document).ready(function() {
        $('.chart').easyPieChart({
            barColor: '#f8ac59',
//                scaleColor: false,
            scaleLength: 5,
            lineWidth: 4,
            size: 80
        });

        $('.chart2').easyPieChart({
            barColor: '#1c84c6',
//                scaleColor: false,
            scaleLength: 5,
            lineWidth: 4,
            size: 80
        });

        var data2 = [
            [gd(2012, 1, 1), 7], [gd(2012, 1, 2), 6], [gd(2012, 1, 3), 4], [gd(2012, 1, 4), 8],
            [gd(2012, 1, 5), 9], [gd(2012, 1, 6), 7], [gd(2012, 1, 7), 5], [gd(2012, 1, 8), 4],
            [gd(2012, 1, 9), 7], [gd(2012, 1, 10), 8], [gd(2012, 1, 11), 9], [gd(2012, 1, 12), 6],
            [gd(2012, 1, 13), 4], [gd(2012, 1, 14), 5], [gd(2012, 1, 15), 11], [gd(2012, 1, 16), 8],
            [gd(2012, 1, 17), 8], [gd(2012, 1, 18), 11], [gd(2012, 1, 19), 11], [gd(2012, 1, 20), 6],
            [gd(2012, 1, 21), 6], [gd(2012, 1, 22), 8], [gd(2012, 1, 23), 11], [gd(2012, 1, 24), 13],
            [gd(2012, 1, 25), 7], [gd(2012, 1, 26), 9], [gd(2012, 1, 27), 9], [gd(2012, 1, 28), 8],
            [gd(2012, 1, 29), 5], [gd(2012, 1, 30), 8], [gd(2012, 1, 31), 25]
        ];

        var data3 = [
            [gd(2012, 1, 1), 800], [gd(2012, 1, 2), 500], [gd(2012, 1, 3), 600], [gd(2012, 1, 4), 700],
            [gd(2012, 1, 5), 500], [gd(2012, 1, 6), 456], [gd(2012, 1, 7), 800], [gd(2012, 1, 8), 589],
            [gd(2012, 1, 9), 467], [gd(2012, 1, 10), 876], [gd(2012, 1, 11), 689], [gd(2012, 1, 12), 700],
            [gd(2012, 1, 13), 500], [gd(2012, 1, 14), 600], [gd(2012, 1, 15), 700], [gd(2012, 1, 16), 786],
            [gd(2012, 1, 17), 345], [gd(2012, 1, 18), 888], [gd(2012, 1, 19), 888], [gd(2012, 1, 20), 888],
            [gd(2012, 1, 21), 987], [gd(2012, 1, 22), 444], [gd(2012, 1, 23), 999], [gd(2012, 1, 24), 567],
            [gd(2012, 1, 25), 786], [gd(2012, 1, 26), 666], [gd(2012, 1, 27), 888], [gd(2012, 1, 28), 900],
            [gd(2012, 1, 29), 178], [gd(2012, 1, 30), 555], [gd(2012, 1, 31), 993]
        ];


        var dataset = [
            {
                label: "Number of orders",
                data: data3,
                color: "#1ab394",
                bars: {
                    show: true,
                    align: "center",
                    barWidth: 24 * 60 * 60 * 600,
                    lineWidth:0
                }

            }, {
                label: "Payments",
                data: data2,
                yaxis: 2,
                color: "#1C84C6",
                lines: {
                    lineWidth:1,
                    show: true,
                    fill: true,
                    fillColor: {
                        colors: [{
                            opacity: 0.2
                        }, {
                            opacity: 0.4
                        }]
                    }
                },
                splines: {
                    show: false,
                    tension: 0.6,
                    lineWidth: 1,
                    fill: 0.1
                },
            }
        ];


        var options = {
            xaxis: {
                mode: "time",
                tickSize: [3, "day"],
                tickLength: 0,
                axisLabel: "Date",
                axisLabelUseCanvas: true,
                axisLabelFontSizePixels: 12,
                axisLabelFontFamily: 'Arial',
                axisLabelPadding: 10,
                color: "#d5d5d5"
            },
            yaxes: [{
                position: "left",
                max: 1070,
                color: "#d5d5d5",
                axisLabelUseCanvas: true,
                axisLabelFontSizePixels: 12,
                axisLabelFontFamily: 'Arial',
                axisLabelPadding: 3
            }, {
                position: "right",
                clolor: "#d5d5d5",
                axisLabelUseCanvas: true,
                axisLabelFontSizePixels: 12,
                axisLabelFontFamily: ' Arial',
                axisLabelPadding: 67
            }
            ],
            legend: {
                noColumns: 1,
                labelBoxBorderColor: "#000000",
                position: "nw"
            },
            grid: {
                hoverable: false,
                borderWidth: 0
            }
        };

        function gd(year, month, day) {
            return new Date(year, month - 1, day).getTime();
        }

        var previousPoint = null, previousLabel = null;

        $.plot($("#flot-dashboard-chart"), dataset, options);

        var mapData = {
            "US": 298,
            "SA": 200,
            "DE": 220,
            "FR": 540,
            "CN": 120,
            "AU": 760,
            "BR": 550,
            "IN": 200,
            "GB": 120,
        };

        $('#world-map').vectorMap({
            map: 'world_mill_en',
            backgroundColor: "transparent",
            regionStyle: {
                initial: {
                    fill: '#e4e4e4',
                    "fill-opacity": 0.9,
                    stroke: 'none',
                    "stroke-width": 0,
                    "stroke-opacity": 0
                }
            },

            series: {
                regions: [{
                    values: mapData,
                    scale: ["#1ab394", "#22d6b1"],
                    normalizeFunction: 'polynomial'
                }]
            },
        });
    });
    // $('#data_1 .input-group.date').datepicker({
    //     todayBtn: "linked",
    //     keyboardNavigation: false,
    //     forceParse: false,
    //     calendarWeeks: true,
    //     autoclose: true
    // });

   </script>
   @stack('scripts')

resources/views/layouts/styles.blade.php
@stack('styles')
<link href="{{asset('assets/css/bootstrap.min.css')}}" rel="stylesheet">
<link href="{{asset('assets/css/bootstrap.rtl.min.css')}}" rel="stylesheet">
<link href="{{asset('assets/css/font-awesome/css/font-awesome.css')}}" rel="stylesheet">
<link href="{{asset('assets/css/css/animate.css')}}" rel="stylesheet">
<link href="{{asset('assets/css/css/plugins/jasny/jasny-bootstrap.min.css')}}" rel="stylesheet">
<link href="{{asset('assets/css/css/plugins/datapicker/datepicker3.css')}}" rel="stylesheet">
{{--<link href="{{asset('assets/css/css/plugins/summernote/summernote.css')}}" rel="stylesheet">--}}
{{--<link href="{{asset('assets/css/css/plugins/summernote/summernote-bs3.css')}}" rel="stylesheet">--}}


<link href="{{asset('assets/css/style.css')}}" rel="stylesheet">
<style>
    .note-editor .col-sm-1, .col-sm-2, .col-sm-3, .col-sm-4, .col-sm-5, .col-sm-6, .col-sm-7, .col-sm-8, .col-sm-9, .col-sm-10, .col-sm-11{
        float: right !important;
    }
</style>